#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure_ac
# autospec version: v25
# autospec commit: 9594167
#
# Source0 file verified with key 0x71112AB16CB33B3A (christos@netbsd.org)
#
Name     : file
Version  : 5.46
Release  : 64
URL      : https://astron.com/pub/file/file-5.46.tar.gz
Source0  : https://astron.com/pub/file/file-5.46.tar.gz
Source1  : https://astron.com/pub/file/file-5.46.tar.gz.asc
Source2  : 71112AB16CB33B3A.pkey
Summary  : Magic number recognition library
Group    : Development/Tools
License  : BSD-2-Clause
Requires: file-bin = %{version}-%{release}
Requires: file-data = %{version}-%{release}
Requires: file-lib = %{version}-%{release}
Requires: file-license = %{version}-%{release}
Requires: file-man = %{version}-%{release}
BuildRequires : bzip2-dev
BuildRequires : file
BuildRequires : gnupg
BuildRequires : pkgconfig(zlib)
BuildRequires : zstd-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0001-stateless.patch
Patch2: 0002-decode-ucode.patch
Patch3: backport-b3384a1fbfa1fee99986e5750ab8e700de4f24ad.patch

%description
# How to get started developing
## Auto files
After checking out the source, run the following:

%package bin
Summary: bin components for the file package.
Group: Binaries
Requires: file-data = %{version}-%{release}
Requires: file-license = %{version}-%{release}

%description bin
bin components for the file package.


%package data
Summary: data components for the file package.
Group: Data

%description data
data components for the file package.


%package dev
Summary: dev components for the file package.
Group: Development
Requires: file-lib = %{version}-%{release}
Requires: file-bin = %{version}-%{release}
Requires: file-data = %{version}-%{release}
Provides: file-devel = %{version}-%{release}
Requires: file = %{version}-%{release}

%description dev
dev components for the file package.


%package lib
Summary: lib components for the file package.
Group: Libraries
Requires: file-data = %{version}-%{release}
Requires: file-license = %{version}-%{release}

%description lib
lib components for the file package.


%package license
Summary: license components for the file package.
Group: Default

%description license
license components for the file package.


%package man
Summary: man components for the file package.
Group: Default

%description man
man components for the file package.


%prep
mkdir .gnupg
chmod 700 .gnupg
gpg --homedir .gnupg --import %{SOURCE2}
gpg --homedir .gnupg --status-fd 1 --verify %{SOURCE1} %{SOURCE0} > gpg.status
grep -E '^\[GNUPG:\] (GOODSIG|EXPKEYSIG) 71112AB16CB33B3A' gpg.status
%setup -q -n file-5.46
cd %{_builddir}/file-5.46
%patch -P 1 -p1
%patch -P 2 -p1
%patch -P 3 -p1

%build
## build_prepend content
# see https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/file&id=57279b8f11
CFLAGS="$CFLAGS -pthread"
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1747063693
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%reconfigure --disable-static --disable-seccomp
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1747063693
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/file
cp %{_builddir}/file-%{version}/COPYING %{buildroot}/usr/share/package-licenses/file/9f5bf317af31a6dac50b5f5504aa63b59d05442c || :
cp %{_builddir}/file-%{version}/python/LICENSE %{buildroot}/usr/share/package-licenses/file/6ae41b2c850d4e22cd6b274d4a5e987ccdb3ad84 || :
export GOAMD64=v2
GOAMD64=v2
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/file

%files data
%defattr(-,root,root,-)
/usr/share/file/magic.mgc

%files dev
%defattr(-,root,root,-)
/usr/include/magic.h
/usr/lib64/libmagic.so
/usr/lib64/pkgconfig/libmagic.pc
/usr/share/man/man3/libmagic.3

%files lib
%defattr(-,root,root,-)
/usr/lib64/libmagic.so.1
/usr/lib64/libmagic.so.1.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/file/6ae41b2c850d4e22cd6b274d4a5e987ccdb3ad84
/usr/share/package-licenses/file/9f5bf317af31a6dac50b5f5504aa63b59d05442c

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/file.1
/usr/share/man/man4/magic.4
