#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x71112AB16CB33B3A (christos@netbsd.org)
#
Name     : file
Version  : 5.34
Release  : 34
URL      : ftp://ftp.astron.com/pub/file/file-5.34.tar.gz
Source0  : ftp://ftp.astron.com/pub/file/file-5.34.tar.gz
Source99 : ftp://ftp.astron.com/pub/file/file-5.34.tar.gz.asc
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause
Requires: file-bin
Requires: file-lib
Requires: file-license
Requires: file-data
Requires: file-man
BuildRequires : buildreq-distutils3
BuildRequires : pkgconfig(zlib)
BuildRequires : zlib-dev
Patch1: stateless.patch
Patch2: decode-ucode.patch

%description
Mailing List: file@astron.com
Mailing List archives: http://mailman.astron.com/pipermail/file/
Bug tracker: http://bugs.astron.com/
E-mail: christos@astron.com
Build Status: https://travis-ci.org/file/file

%package bin
Summary: bin components for the file package.
Group: Binaries
Requires: file-data
Requires: file-license
Requires: file-man

%description bin
bin components for the file package.


%package data
Summary: data components for the file package.
Group: Data

%description data
data components for the file package.


%package dev
Summary: dev components for the file package.
Group: Development
Requires: file-lib
Requires: file-bin
Requires: file-data
Provides: file-devel

%description dev
dev components for the file package.


%package lib
Summary: lib components for the file package.
Group: Libraries
Requires: file-data
Requires: file-license

%description lib
lib components for the file package.


%package license
Summary: license components for the file package.
Group: Default

%description license
license components for the file package.


%package man
Summary: man components for the file package.
Group: Default

%description man
man components for the file package.


%prep
%setup -q -n file-5.34
%patch1 -p1
%patch2 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1536633941
%reconfigure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1536633941
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/file
cp COPYING %{buildroot}/usr/share/doc/file/COPYING
cp python/LICENSE %{buildroot}/usr/share/doc/file/python_LICENSE
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/file

%files data
%defattr(-,root,root,-)
/usr/share/file/magic.mgc

%files dev
%defattr(-,root,root,-)
/usr/include/magic.h
/usr/lib64/libmagic.so
/usr/share/man/man3/libmagic.3

%files lib
%defattr(-,root,root,-)
/usr/lib64/libmagic.so.1
/usr/lib64/libmagic.so.1.0.0

%files license
%defattr(-,root,root,-)
/usr/share/doc/file/COPYING
/usr/share/doc/file/python_LICENSE

%files man
%defattr(-,root,root,-)
/usr/share/man/man1/file.1
/usr/share/man/man4/magic.4
