#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x71112AB16CB33B3A (christos@netbsd.org)
#
Name     : file
Version  : 5.38
Release  : 52
URL      : https://astron.com/pub/file/file-5.38.tar.gz
Source0  : https://astron.com/pub/file/file-5.38.tar.gz
Source1  : https://astron.com/pub/file/file-5.38.tar.gz.asc
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause
Requires: file-bin = %{version}-%{release}
Requires: file-data = %{version}-%{release}
Requires: file-lib = %{version}-%{release}
Requires: file-license = %{version}-%{release}
Requires: file-man = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : bzip2-dev
BuildRequires : pkgconfig(zlib)
BuildRequires : xz-dev
Patch1: 0001-stateless.patch
Patch2: 0002-decode-ucode.patch

%description
Mailing List: file@astron.com
Mailing List archives: http://mailman.astron.com/pipermail/file/
Bug tracker: http://bugs.astron.com/
E-mail: christos@astron.com
Build Status: https://travis-ci.org/file/file

%package bin
Summary: bin components for the file package.
Group: Binaries
Requires: file-data = %{version}-%{release}
Requires: file-license = %{version}-%{release}

%description bin
bin components for the file package.


%package data
Summary: data components for the file package.
Group: Data

%description data
data components for the file package.


%package dev
Summary: dev components for the file package.
Group: Development
Requires: file-lib = %{version}-%{release}
Requires: file-bin = %{version}-%{release}
Requires: file-data = %{version}-%{release}
Provides: file-devel = %{version}-%{release}
Requires: file = %{version}-%{release}

%description dev
dev components for the file package.


%package lib
Summary: lib components for the file package.
Group: Libraries
Requires: file-data = %{version}-%{release}
Requires: file-license = %{version}-%{release}

%description lib
lib components for the file package.


%package license
Summary: license components for the file package.
Group: Default

%description license
license components for the file package.


%package man
Summary: man components for the file package.
Group: Default

%description man
man components for the file package.


%prep
%setup -q -n file-5.38
cd %{_builddir}/file-5.38
%patch1 -p1
%patch2 -p1

%build
## build_prepend content
# see https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/file&id=57279b8f11
CFLAGS="$CFLAGS -pthread"
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1582235560
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto -fstack-protector-strong -mzero-caller-saved-regs=used "
export FCFLAGS="$CFLAGS -fno-lto -fstack-protector-strong -mzero-caller-saved-regs=used "
export FFLAGS="$CFLAGS -fno-lto -fstack-protector-strong -mzero-caller-saved-regs=used "
export CXXFLAGS="$CXXFLAGS -fno-lto -fstack-protector-strong -mzero-caller-saved-regs=used "
%reconfigure --disable-static --disable-seccomp
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1582235560
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/file
cp %{_builddir}/file-5.38/COPYING %{buildroot}/usr/share/package-licenses/file/9f5bf317af31a6dac50b5f5504aa63b59d05442c
cp %{_builddir}/file-5.38/python/LICENSE %{buildroot}/usr/share/package-licenses/file/6ae41b2c850d4e22cd6b274d4a5e987ccdb3ad84
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/file

%files data
%defattr(-,root,root,-)
/usr/share/file/magic.mgc

%files dev
%defattr(-,root,root,-)
/usr/include/magic.h
/usr/lib64/libmagic.so
/usr/share/man/man3/libmagic.3

%files lib
%defattr(-,root,root,-)
/usr/lib64/libmagic.so.1
/usr/lib64/libmagic.so.1.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/file/6ae41b2c850d4e22cd6b274d4a5e987ccdb3ad84
/usr/share/package-licenses/file/9f5bf317af31a6dac50b5f5504aa63b59d05442c

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/file.1
/usr/share/man/man4/magic.4
